import { MISSIONS, missionById } from "./missions.js";
import { makeBoard, publicBoard, resolve, safeComplete } from "./engine.js";
import { openStorage, transaction, read, put, now } from "./storage.js";

let database;
const fail = (code, message) => Object.assign(new Error(message), { code });
const id = () => globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const seed = () => Math.floor(Math.random() * 0x7fffffff) + 1;
const snapshot = (attempt, terminal = attempt.status !== "active") => ({ id: attempt.id, missionId: attempt.missionId, status: attempt.status, score: attempt.score, clearCount: attempt.clearCount, scanCount: attempt.scanCount, markCount: attempt.markCount, startedAt: attempt.startedAt, finishedAt: attempt.finishedAt || null, board: publicBoard(attempt.boardState, terminal) });
const missionCard = (mission, progress) => ({ id: mission.id, slug: mission.slug, title: mission.title, briefing: mission.briefing, grid: { rows: mission.rows, columns: mission.columns }, threatCategories: Object.keys(mission.threats), targetScore: mission.targetScore, locked: mission.order !== 1 && !progress.has(mission.id - 1), completed: progress.has(mission.id), bestScore: progress.get(mission.id)?.bestScore || 0, bestRating: progress.get(mission.id)?.bestRating || 0 });
async function profileAndProgress(api) { let profile = await read(api.profile, "local"); if (!profile) { profile = { soundEnabled: true, createdAt: now(), updatedAt: now() }; await put(api.profile, profile, "local"); } const records = await new Promise((resolve, reject) => { const request = api.missionProgress.getAll(); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); return { profile, progress: new Map(records.map((record) => [record.missionId, record])) }; }
const writeEvent = async (api, attempt, eventType, payload) => { attempt.eventSequence = (attempt.eventSequence || 0) + 1; await put(api.attemptEvents, { attemptId: attempt.id, sequence: attempt.eventSequence, eventType, payload, createdAt: now() }); };
async function bootstrap() { return transaction(database, "readwrite", async (api) => { const { profile, progress } = await profileAndProgress(api); const active = await read(api.activeMission, "current"); const activeAttempt = active ? await read(api.attempts, active.attemptId) : null; return { player: { soundEnabled: profile.soundEnabled, updatedAt: profile.updatedAt }, missions: MISSIONS.map((mission) => missionCard(mission, progress)), activeAttempt: activeAttempt?.status === "active" ? snapshot(activeAttempt) : null }; }); }
async function startAttempt({ missionId, restart = false }) { return transaction(database, "readwrite", async (api) => { const mission = missionById(missionId); if (!mission) throw fail("not_found", "Mission was not found."); const { progress } = await profileAndProgress(api); if (mission.order !== 1 && !progress.has(mission.id - 1)) throw fail("mission_locked", "Mission is locked."); const current = await read(api.activeMission, "current"); const existing = current ? await read(api.attempts, current.attemptId) : null; if (existing?.status === "active" && existing.missionId === mission.id && !restart) return snapshot(existing); if (existing?.status === "active") { existing.status = "abandoned"; existing.finishedAt = now(); await writeEvent(api, existing, "abandon", {}); await put(api.attempts, existing); }
  const boardSeed = seed(), attempt = { id: id(), missionId: mission.id, status: "active", boardSeed, boardState: makeBoard(mission, boardSeed), score: 0, clearCount: 0, scanCount: 0, markCount: 0, startedAt: now(), finishedAt: null, eventSequence: 0 }; await writeEvent(api, attempt, "start", { missionId: mission.id }); await put(api.attempts, attempt); await put(api.activeMission, { missionId: mission.id, attemptId: attempt.id }, "current"); return snapshot(attempt); }); }
async function getAttempt({ attemptId }) { return transaction(database, "readonly", async (api) => { const attempt = await read(api.attempts, attemptId); if (!attempt) throw fail("not_found", "Attempt was not found."); return snapshot(attempt); }); }
async function act({ attemptId, type, row, column }) { return transaction(database, "readwrite", async (api) => { if (typeof attemptId !== "string" || !Number.isInteger(row) || !Number.isInteger(column) || !["scan", "clear", "mark"].includes(type)) throw fail("invalid_request", "Action payload is malformed."); const attempt = await read(api.attempts, attemptId); if (!attempt) throw fail("not_found", "Attempt was not found."); if (attempt.status !== "active") throw fail("attempt_inactive", "Attempt is no longer active."); const mission = missionById(attempt.missionId); let resolution; try { resolution = resolve(attempt.boardState, type, row, column, attempt.boardSeed + attempt.scanCount + attempt.clearCount); } catch (error) { throw fail("invalid_action", error.message); }
  attempt.clearCount += resolution.clears; attempt.scanCount += resolution.scans; if (type === "mark") attempt.markCount += attempt.boardState.cells[row][column].state === "marked" ? 1 : -1; attempt.score += resolution.clears * 10 - (resolution.scans ? 2 : 0); let result = null;
  if (resolution.failed) { attempt.status = "failed"; attempt.finishedAt = now(); resolution.events.push("failure"); result = { outcome: "failure", score: attempt.score, rating: 0, newBest: false, unlockedMissionId: null }; }
  else if (safeComplete(attempt.boardState)) { attempt.status = "succeeded"; attempt.finishedAt = now(); attempt.score += Math.max(0, 20 - attempt.scanCount) * 2 + Math.max(0, attempt.markCount); const rating = attempt.score >= mission.targetScore ? 3 : attempt.score >= mission.targetScore * .65 ? 2 : 1; const old = (await read(api.missionProgress, mission.id)); const newBest = !old || attempt.score > old.bestScore; await put(api.missionProgress, { missionId: mission.id, completedAt: old?.completedAt || now(), bestScore: Math.max(old?.bestScore || 0, attempt.score), bestRating: Math.max(old?.bestRating || 0, rating) }); resolution.events.push("success"); result = { outcome: "success", score: attempt.score, rating, newBest, unlockedMissionId: mission.order < MISSIONS.length ? mission.id + 1 : null }; }
  await writeEvent(api, attempt, type, { row, column, effects: resolution.effects }); for (const item of resolution.effects) await writeEvent(api, attempt, "effect", item); await put(api.attempts, attempt); if (attempt.status !== "active") await put(api.activeMission, null, "current"); return { attempt: snapshot(attempt, Boolean(result)), action: { type, row, column }, effects: resolution.effects, events: resolution.events, result }; }); }
async function abandonAttempt({ attemptId }) { return transaction(database, "readwrite", async (api) => { const attempt = await read(api.attempts, attemptId); if (!attempt) throw fail("not_found", "Attempt was not found."); if (attempt.status === "active") { attempt.status = "abandoned"; attempt.finishedAt = now(); await writeEvent(api, attempt, "abandon", {}); await put(api.attempts, attempt); await put(api.activeMission, null, "current"); } return snapshot(attempt); }); }
const commands = { bootstrap, setSoundEnabled: async ({ soundEnabled }) => { if (typeof soundEnabled !== "boolean") throw fail("invalid_request", "soundEnabled must be boolean."); return transaction(database, "readwrite", async (api) => { const { profile } = await profileAndProgress(api); profile.soundEnabled = soundEnabled; profile.updatedAt = now(); await put(api.profile, profile, "local"); return { soundEnabled, updatedAt: profile.updatedAt }; }); }, startAttempt, getAttempt, act, abandonAttempt };
self.onmessage = async ({ data }) => { const { id: requestId, command, payload = {} } = data || {}; if (typeof requestId !== "string" || typeof command !== "string") return; try { database ||= await openStorage(); if (!commands[command]) throw fail("invalid_request", "Unknown command."); self.postMessage({ id: requestId, ok: true, data: await commands[command](payload) }); } catch (error) { self.postMessage({ id: requestId, ok: false, error: { code: error.code || "internal_error", message: error.message || "Local game authority failed." } }); } };
